### ISSUE TITLE
LEDs Ethernet y Wifi

### ISSUE THREAD

**Issue by gattofernando** [DataloggersSolar/IssueTracker#12]
Los LEDs del panel que indican si hay wifi y Ethernet los maneja el ESP32. El de Ethernet está conectado al GPIO5. Y el de WIFI está conectado a GPIO36. Se activan con un 1 lógico. Hacer los cambios necesarios para que se funcione correctamente

**Comment by marianoronchi** [comment]
Se cambia el 36 a 17 porque el 36 no puede setearse como output.

**Comment by marianoronchi** [comment]
Se envía el estado de los LEDS por Modbus
